version: "3"
networks:
  app-otus-study:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    networks:
      - app-otus-study
    ports:
      - 9002:9000
    volumes:
      - ./code/:/srv/code
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: webserver
    ports:
      - 10000:80
      - 10001:443
    volumes_from:
      - app
    restart: always
    networks:
      - app-otus-study
  db:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    container_name: db
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - 15306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-otus-study
