version: '3'

services:
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: dockertest/php 
    container_name: app_dockertest
    volumes:
       - ./code:/data/dockertest.loc
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: dockertest/nginx
    container_name: webserver_dockertest
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./code:/data/dockertest.loc
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db_dockertest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql  
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: redis_dockertest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  memcached:
    image: memcached:1
    container_name: memcached_dockertest
    ports:
      - "11211:11211"

networks:
  app-network:
    driver: bridge 