before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_server1:
  stage: deploy
  environment:
    name: server
    url: $SERVER
  script:
    - ssh $SSH_USER@$SERVER "sudo rm -rf /var/www/inspacient &&
      cd /var/www &&
      git clone https://deploy:nSsqF6ssFhwLFNcjhsn9@gitlab.com/profox/inspacient.git inspacient &&
      sudo chown www-data:www-data inspacient -R &&
      cd inspacient &&
      sh ./deploy.sh $SERVER $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD"
  only:
    - main
