stages:
  - "deploy"

deploy:
  stage: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - echo "$SSH_PRIVATE_KEY"
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - export NEW_APP_DIR=$(date +build_%Y%m%d%H%M%S)
  script:
    - ssh $REMOTE_SERVER_USER@$REMOTE_SERVER_HOST "cd /var/www/otus.local &&
      rm -rf ./settings/ &&
      git clone git@gitlab.com:TmBombadil/otus18_deploy_settings.git settings &&
      git clone git@gitlab.com:TmBombadil/otus18.git $NEW_APP_DIR &&
      cd $NEW_APP_DIR && chmod +x deploy.sh &&
      sh ./deploy.sh $NEW_APP_DIR $IMAGE_NAME:$IMAGE_SHA' &&
      rm -rf ../settings/"
