image: docker:24.0
services:
  - name: docker:24.0-dind
    alias: docker

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - docker compose down || true
    - mkdir -p /home/vlad/my_app
    - rm -rf /home/vlad/my_app/*
    - cp -R ./code/* /home/vlad/my_app/
    - cd /home/vlad/my_app
    - composer install
    - cd -
    - docker compose up -d --build