-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS cinema.halls
(
    id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.seats
(
    hall_id integer NOT NULL,
    "row" integer NOT NULL,
    price_zone_id integer NOT NULL,
    "number" integer NOT NULL,
    id serial NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.movies
(
    id serial NOT NULL,
    name character varying NOT NULL,
    short_description character varying,
    full_description character varying,
    duration integer NOT NULL,
    release_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.sessions
(
    id serial NOT NULL,
    movie_id integer NOT NULL,
    begin timestamp with time zone NOT NULL,
    "end" timestamp with time zone NOT NULL,
    hall_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.bookings
(
    id serial NOT NULL,
    session_id integer NOT NULL,
    seat_id integer NOT NULL,
    customer_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.customers
(
    id serial NOT NULL,
    name character varying NOT NULL,
    phone character varying,
    email character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.price_zones
(
    id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cinema.prices
(
    id serial NOT NULL,
    price_zone_id integer NOT NULL,
    session_id integer NOT NULL,
    amount numeric NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE cinema.seats
    ADD FOREIGN KEY (price_zone_id)
    REFERENCES cinema.price_zones (id)
    NOT VALID;


ALTER TABLE cinema.seats
    ADD FOREIGN KEY (hall_id)
    REFERENCES cinema.halls (id)
    NOT VALID;


ALTER TABLE cinema.sessions
    ADD FOREIGN KEY (movie_id)
    REFERENCES cinema.movies (id)
    NOT VALID;


ALTER TABLE cinema.sessions
    ADD FOREIGN KEY (hall_id)
    REFERENCES cinema.halls (id)
    NOT VALID;


ALTER TABLE cinema.prices
    ADD FOREIGN KEY (price_zone_id)
    REFERENCES cinema.price_zones (id)
    NOT VALID;


ALTER TABLE cinema.prices
    ADD FOREIGN KEY (session_id)
    REFERENCES cinema.sessions (id)
    NOT VALID;


ALTER TABLE cinema.bookings
    ADD FOREIGN KEY (session_id)
    REFERENCES cinema.sessions (id)
    NOT VALID;


ALTER TABLE cinema.bookings
    ADD FOREIGN KEY (seat_id)
    REFERENCES cinema.seats (id)
    NOT VALID;


ALTER TABLE cinema.bookings
    ADD FOREIGN KEY (customer_id)
    REFERENCES cinema.customers (id)
    NOT VALID;

END;