CREATE TABLE cinema_hall (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) UNIQUE,
	PRIMARY KEY(id)
);

CREATE TABLE film (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150),
	price NUMERIC(6,2) NOT NULL,
	duration INT UNSIGNED NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE tariff (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL UNIQUE,
	ratio NUMERIC(3,2) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE cinema_session (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	hall_id INT UNSIGNED NOT NULL,
	film_id INT UNSIGNED NOT NULL,
	tariff_id INT UNSIGNED NOT NULL,
	start_time DATETIME NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(hall_id) REFERENCES cinema_hall(id),
	FOREIGN KEY(film_id) REFERENCES film(id),
	FOREIGN KEY(tariff_id) REFERENCES tariff(id),
	CONSTRAINT unique_hall_film_start
	UNIQUE KEY(hall_id, film_id, start_time)
);

CREATE TABLE hall_seat (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	row SMALLINT UNSIGNED NOT NULL,
	seat SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT unique_row_seat
	UNIQUE KEY(row, seat)
);

CREATE TABLE user (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL,
	phone VARCHAR(30) NOT NULL UNIQUE,
	PRIMARY KEY(id)
);

CREATE TABLE tickets (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	seat_id INT UNSIGNED NOT NULL,
	session_id INT UNSIGNED NOT NULL,
	total_price NUMERIC(6,2) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(seat_id) REFERENCES hall_seat(id),
	FOREIGN KEY(session_id) REFERENCES cinema_session(id),
	CONSTRAINT unique_session_seat
	UNIQUE KEY(session_id, seat_id)
);