version: "3"
services:

  balancer:
    build:
      context: .docker/balancer
      dockerfile: Dockerfile
    container_name: brackets-balancer
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2
    networks:
      - trusted-brackets


  webserver1:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    container_name: webserver1
    ports:
      - "3000:80"
    depends_on:
      - php1
      - php2
    volumes:
      - ./src:/var/www/trusted-brackets.local
    networks:
      - trusted-brackets

  webserver2:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    container_name: webserver2
    ports:
      - "3001:80"
    depends_on:
      - php1
      - php2
    volumes:
      - ./src:/var/www/trusted-brackets.local
    networks:
      - trusted-brackets

  php1:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: brackets-php1
    volumes:
      - ./src:/var/www/trusted-brackets.local
    networks:
      - trusted-brackets

  php2:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: brackets-php2
    volumes:
      - ./src:/var/www/trusted-brackets.local
    networks:
      - trusted-brackets


  memcached1:
    image: oktec/repcached:latest
    container_name: brackets-memcached1
    restart: unless-stopped
    environment:
      SLAVE: memcached2
    ports:
      - "11221:11211"
    networks:
      - trusted-brackets


  memcached2:
    image: oktec/repcached:latest
    container_name: brackets-memcached2
    restart: unless-stopped
    environment:
      SLAVE: memcached1
    ports:
      - "11222:11211"
    networks:
      - trusted-brackets


networks:
  trusted-brackets:
    driver: bridge