version: '3.8'

services:
  webserver:
    image: nginx:alpine
    container_name: otusapp-nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./code:/data
    networks:
      - otusapp-network
    depends_on:
      - backend

  backend:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: otusapp-php
    volumes:
      - ./code:/data
    networks:
      - otusapp-network
    depends_on:
      - memcached

  memcached:
    image: memcached:alpine
    container_name: otusapp-memcached
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      - otusapp-network

networks:
  otusapp-network:
    driver: bridge

volumes:
  otusapp-database-data:
