version: '3.8'

services:
  backend-server:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: otusapp-php-server
    volumes:
      - ./code:/data
      - otusapp-tmp-data:/tmp
    networks:
      - otusapp-network
  backend-client:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: otusapp-php-client
    volumes:
      - ./code:/data
      - otusapp-tmp-data:/tmp
    networks:
      - otusapp-network

networks:
  otusapp-network:
    driver: bridge

volumes:
  otusapp-tmp-data:
