version: "3.0"
services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx.dockerfile
    image: otus/nginx
    restart: always
    volumes:
      - ../../code/public:/app/public
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:8888:80
    networks:
      - otus-network

  app:
    build:
      context: ..
      dockerfile: docker/app.dockerfile
    image: otus/app
    restart: always
    volumes:
      - ../../code:/app
    networks:
      - otus-network

  mysql:
    build:
      context: ..
      dockerfile: docker/mysql.dockerfile
    image: otus/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:33066:3306
    networks:
      - otus-network

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - otus-network

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - otus-network

networks:
  otus-network:
    driver: bridge
