# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP, назовём его app
  app-server:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: app_server # имя контейнера после запуска
    volumes:
       - ./code:/data/application.local
       - ./code/tmp:/data/application.local/tmp
#       - ./fpm/config/php.ini:/usr/local/etc/php/php.ini
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  app-client:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: app_client # имя контейнера после запуска
    volumes:
      - ./code:/data/application.local
      - ./code/tmp:/data/application.local/tmp
#      - ./fpm/config/php.ini:/usr/local/etc/php/php.ini
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge