version: '3'

services:
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: aemets/php
    container_name: app
    volumes:
       - ./code:/data/anyhost
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: aemets/nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./code:/data/anyhost
    networks:
      - app-network

networks:
  app-network:
    driver: bridge