version: '3'

services:
  sockets-client:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: sockets/client
    container_name: sockets-client
    volumes:
      - ./project:/data
      - ./socket:/tmp

