version: "3.7"

services:
  php_service:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - "./../:/var/www/html"
      - "./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
      - "./phpsocket:/var/run/php-fpm"

  nginx_service:
    image: nginx:1.17
    ports:
      - "${APP_PORT}:80"
    volumes:
      - "./nginx/log:/var/www/log"
      - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./phpsocket:/var/run/php-fpm"
    depends_on:
      - php_service
