version: '3'

services:

  php:
    image: fpm
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: cont_fpm
    volumes:
      - ./src:/src/appdocker.local
    networks:
     - app-network
    

  webserverng:
    image: webserverng
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cont_webserverng
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/src/appdocker.local
    networks:
      - app-network
    environment:
      - NGINX_HOST=appdocker.local
      - NGINX_PORT=80


  redis:
    build: ./redis
    container_name: cont_redis
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - app-network

  memcached:
    image: memcached
    container_name: cont_memcached   
    restart: always
    networks:
      - app-network

  db:
    image: mysql
    container_name: cont_mysql    
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge