# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP, назовём его app
  app:
    container_name: app # имя контейнера после запуска
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: dockerapp/php # имя будущего образа
    volumes:
      - ../code:/data/docker.application.local
      - "phpsocket:/var/run"
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MEMCACHED_PORT: ${MEMCACHED_PORT}

  #контейне с Nginx
  webserver:
    container_name: webserver
    image: dockerapp/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # проброс портов
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../code:/data/docker.application.local
      - "phpsocket:/var/run"
    networks:
      - app-network

  # контейнер с MySQL
  # строим на базе стандартного образа
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    # описываем, какую БД мы создаём
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network
    links:
      - app

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - ${MEMCACHED_PORT}:${MEMCACHED_PORT}
    networks:
      - app-network
    links:
      - app

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  phpsocket:
