version: "3.0"
services:
  balancer:
    build:
      context: ..
      dockerfile: docker/balancer/nginx.dockerfile
    restart: always
    volumes:
      - ../src/public:/app/public
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 127.0.0.1:8800:80
    networks:
      - otus-network

  nginx_backend_1:
    build:
      context: ..
      dockerfile: docker/nginx_backend_1/nginx.dockerfile
    restart: always
    volumes:
      - ../src/public:/app/public
      - ./nginx_backend_1/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_backend_1/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - otus-network

  app_backend_1:
    build:
      context: ..
      dockerfile: docker/app_backend_1/app.dockerfile
    restart: always
    volumes:
      - ../src:/app
    networks:
      - otus-network

  nginx_backend_2:
    build:
      context: ..
      dockerfile: docker/nginx_backend_2/nginx.dockerfile
    restart: always
    volumes:
      - ../src/public:/app/public
      - ./nginx_backend_2/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_backend_2/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - otus-network

  app_backend_2:
    build:
      context: ..
      dockerfile: docker/app_backend_2/app.dockerfile
    restart: always
    volumes:
      - ../src:/app
    networks:
      - otus-network

  memcached:
    build:
      context: ..
      dockerfile: docker/memcached.dockerfile
    networks:
      - otus-network

networks:
  otus-network:
    driver: bridge
