version: "3.7"

services:
  web:
    build: ./nginx
    ports:
      - 8085:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/code:/var/www/otus
    restart: always
    networks:
      - otus

  php:
    build: ./php-fpm
    volumes:
      - ./nginx/code:/var/www/otus
    restart: always
    networks:
      - otus

  redis:
    build: ./redis
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - otus

  memcached:
    image: memcached:1.6.10-alpine
    restart: always
    networks:
      - otus

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    networks:
      - otus

networks:
  otus:
    driver: bridge
