version: '3.5'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@mail.ru"
      - "PGADMIN_DEFAULT_PASSWORD=root"
    ports:
      - "8082:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_entrypoint:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
