# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP, назовём его app
  app:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: app # имя контейнера после запуска
    volumes:
      - ./code:/data/mysite.local
      - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsocket:/var/run
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  #контейне с Nginx
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    # проброс портов
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
      - phpsocket:/var/run
    networks:
      - app-network

  # контейнер с MySQL
  # строим на базе стандартного образа
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    # описываем, какую БД мы создаём
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

  # контейнер с redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis/data:/var/lib/redis
    networks:
      - app-network

  # Контейнер с memcached
  memcached:
      container_name: memcached
      image: memcached:latest
      ports:
        - "11211:11211"
      networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  phpsocket: