version: '3'

services:
  app:
    build:
      context: ./php7.4-fpm
      dockerfile: Dockerfile
    image: hw4/php
    container_name: hw4.php
    volumes:
       - ./code:/var/www/homework.loc
       - ./php7.4-fpm/php.ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: hw4/nginx
    container_name: hw4.nginx
    ports:
      - "80:80"
    volumes:
       - ./code:/var/www/homework.loc
    networks:
      - app-network

networks:
  app-network:
    driver: bridge