version: "3.7"

services:
  php-chat-server:
    build:
      context: ""
      dockerfile: php/Dockerfile
    volumes:
      - "./../:/var/www/html"
      - "./chat:/tmp/chat"
    command: /bin/sh -c "composer install && rm -f /tmp/chat/chat.sock && php app.php server"
    stdin_open: true
    tty: true

  php-chat-client:
    build:
      context: ""
      dockerfile: php/Dockerfile
    volumes:
      - "./../:/var/www/html"
      - "./chat:/tmp/chat"
    command: /bin/sh -c "composer install && php app.php client"
    stdin_open: true
    tty: true
