FROM nginx:latest

ARG UID

RUN addgroup --gid $UID --system app \
    && adduser --uid $UID --system --disabled-login --disabled-password --gid $UID app

WORKDIR /var/www
VOLUME /var/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]