# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:


  #контейне с Nginx
  webserver18:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx18
    container_name: webserver18
    # проброс портов
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  #Контейнер с PHP, назовём его app
  app18:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php18 # имя будущего образа
    container_name: app18 # имя контейнера после запуска
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge