version: '3'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: validation/php
    container_name: app
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: validation/nginx
    container_name: webserver
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge