version: '3'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_php_fpm 
    ports:
      - "9000:9000"
    volumes:
      - ./fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./code:/data/mysite.local
    networks:
      - app-network

  webserver:
    container_name: ${PROJECT_NAME}_webserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_nginx
    ports:
      - "83:80"
      - "443:443"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

