version: '3'

services:
  #nginx
  nginx:
    build:
      context: ./conf/nginx/
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/snikonov.local
    networks:
      - app-network
  #php-fpm
  app:
    build:
      context: ./conf/fpm
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-fpm
    volumes:
      - ./app:/var/www/snikonov.local
    networks:
      - app-network
  #redis
  redis:
    image: redis:latest
    container_name: ${APP_NAME}-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  #memcached
  memchached:
    image: memcached:latest
    container_name: ${APP_NAME}-memcached
    ports:
      - "11211:11211"
    networks:
      - app-network
  #db
  db:
    image: mysql:5.7.34
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: ${APP_NAME}-adminer
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
