-- Таблица кинозалов
CREATE TABLE public.cinema_screens
(
    id        int2        NOT NULL,
    "name"    varchar(50) NOT NULL,
    max_seats int2        NOT NULL,
    CONSTRAINT cinema_screens_pk PRIMARY KEY (id)
);

-- Таблица фильмов
CREATE TABLE public.cinema_movies
(
    id            int4        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name_original varchar(50) NOT NULL,
    name_loc      varchar(50) NULL,
    duration_min  int2        NOT NULL,
    CONSTRAINT cinema_movies_pk PRIMARY KEY (id)
);

-- Таблица киносеансов
CREATE TABLE public.cinema_sessions
(
    id            int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    movie_id      int4         NOT NULL,
    screen_id     int2         NOT NULL,
    session_start timestamp(0) NOT NULL,
    CONSTRAINT cinema_sessions_pk PRIMARY KEY (id),
    CONSTRAINT cinema_sessions_un UNIQUE (screen_id, session_start),
    CONSTRAINT cinema_sessions_movies_fk FOREIGN KEY (movie_id) REFERENCES cinema_movies (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT cinema_sessions_screens_fk FOREIGN KEY (screen_id) REFERENCES cinema_screens (id) ON UPDATE CASCADE ON DELETE CASCADE
);
